#!/bin/sh

set -e

: "${JEKYLL_BUILD_OPTIONS:=}"

if [ `id -u` -eq 0 ]; then
    echo "Running $0 as nginx"
    su -s /bin/sh -c "$0" nginx
    exit $?
fi

cd /source

jekyll build --destination /site --watch ${JEKYLL_BUILD_OPTIONS}
